version: '2.1'
networks:
  eemessengernet:
    driver: bridge
volumes:
  postgresql-etc: {}
  postgresql-data: {}
services:
  selenium-hub:
    image: selenium/hub:3.141.59-vanadium
    ports:
      - "4444:4444"
    networks: [eemessengernet]
  chrome:
    image: selenium/node-chrome:3.141.59-vanadium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
    networks: [eemessengernet]
  postgresql:
    image: healthcheck/postgres:latest
    environment:
      POSTGRES_DB: eemessenger
      POSTGRES_USER: eemessenger
      POSTGRES_PASSWORD: eemessenger
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
    volumes:
      - postgresql-data:/var/lib/postgresql:rw
      - postgresql-etc:/etc/postgresql:rw
    ports: ['5432']
    networks: [eemessengernet]
  jboss:
    depends_on:
      postgresql:
        condition: service_healthy
    build:
      context: ..
      dockerfile: ""
    ports: ['8080:8080']
    environment:
      POSTGRES_DB: eemessenger
      POSTGRES_USER: eemessenger
      POSTGRES_PASSWORD: eemessenger
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
    networks: [eemessengernet]
  healthcheck:
    image: alpine
    depends_on:
      jboss:
        condition: service_healthy
