version: '2.1'
networks:
  strutsnet:
    driver: bridge
volumes:
  mysql-etc: {}
  mysql-data: {}
services:
  selenium-hub:
    image: selenium/hub:3.141.59-vanadium
    ports:
      - "4444:4444"
    networks: [strutsnet]
  chrome:
    image: selenium/node-chrome:3.141.59-vanadium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
    networks: [strutsnet]
  jboss:
    build:
      context: ../
      dockerfile: sdocker/Dockerfile
    ports: ['8080:8080']
    networks: [strutsnet]
  healthcheck:
    image: alpine
    depends_on:
      jboss:
        condition: service_healthy
