version: '2.1'
networks:
  eemessengernet:
    driver: bridge
volumes:
  postgresql-etc: {}
  postgresql-data: {}
services:
  postgresql:
    image: vmalaya/eemessengertestpostgres:${project.version}
    container_name: postgresql
    volumes:
      - postgresql-data:/var/lib/postgresql:rw
      - postgresql-etc:/etc/postgresql:rw
    ports: ['5432']
    networks: [eemessengernet]
    hostname: postgresql
  app:
    image: vmalaya/eemessengertestapp:${project.version}
    container_name: app
    ports: ['8080:8080']
    networks: [eemessengernet]
    depends_on:
      postgresql:
        condition: service_healthy
    hostname: app
#    healthcheck:
#      test: wget -q --spider http://127.0.0.1:8080/eemessenger/ || exit 1
#      retries: 33
#      timeout: 3s
#      interval: 3s
  healthcheck:
    image: alpine
    depends_on:
      app:
        condition: service_healthy
