version: '2.1'
networks:
  eemessengernet:
    driver: bridge
volumes:
  postgresql-etc: {}
  postgresql-data: {}
services:
  selenium-hub:
    image: vmalaya/eemessengertestselenium:${project.version}
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks: [eemessengernet]
  chrome:
    image: vmalaya/eemessengertestchrome:${project.version}
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    networks: [eemessengernet]
  postgresql:
    image: vmalaya/eemessengertestpostgres:${project.version}
    container_name: postgresql
    volumes:
      - postgresql-data:/var/lib/postgresql:rw
      - postgresql-etc:/etc/postgresql:rw
    ports: ['5432']
    networks: [eemessengernet]
    hostname: postgresql
  app:
    image: vmalaya/eemessengertestapp:${project.version}
    container_name: app
    ports: ['8080:8080']
    networks: [eemessengernet]
    depends_on:
      - postgresql
      - chrome
    hostname: app

