version: '2.1'
networks:
  eemessengernet:
    driver: bridge
volumes:
  postgresql-etc: {}
  postgresql-data: {}
services:
  postgresql:
    image: vmalaya/eemessengertestpostgres:1.0.0-SNAPSHOT
    container_name: postgresql
    volumes:
      - postgresql-data:/var/lib/postgresql:rw
      - postgresql-etc:/etc/postgresql:rw
    ports: ['5432']
    networks: [eemessengernet]
    hostname: postgresql
  app:
    image: vmalaya/eemessengertestapp:1.0.0-SNAPSHOT
    container_name: app
    ports: ['8080:8080']
    networks: [eemessengernet]
    depends_on:
      - postgresql
    hostname: app
