version: '2'
services:
  mysql:
    image: mysql
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: strutsdb
    networks:
      - grid
  jboss:
    build: .
    restart: on-failure
    ports:
      - '8080:8080'
      - '9990:9990'
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: strutsdb
networks:
  grid:
    driver: bridge




