version: '2.1'
networks:
  strutssqlnet:
    driver: bridge
volumes:
  mysql-etc: {}
  mysql-data: {}
services:
  selenium-hub:
    image: selenium/hub:3.141.59-vanadium
    ports:
      - "4444:4444"
    networks: [strutssqlnet]
  chrome:
    image: selenium/node-chrome:3.141.59-vanadium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
    networks: [strutssqlnet]
  mysql:
    image: healthcheck/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: strutssql
      MYSQL_USER: strutssql
      MYSQL_DATABASE: strutssql
    volumes:
      - mysql-data:/var/lib/mysql:rw
      - mysql-etc:/etc/mysql:rw
    ports: ['3306']
    networks: [strutssqlnet]
  jboss:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: ../../
      dockerfile: strutssql/docker/Dockerfile
    ports: ['8080:8080']
    environment:
      MYSQL_USER: strutssql
      MYSQL_PASSWORD: strutssql
      MYSQL_DATABASE: strutssql
      MYSQL_HOST: mysql
    networks: [strutssqlnet]
  healthcheck:
    image: alpine
    depends_on:
      jboss:
        condition: service_healthy
